import type { ExampleScene, RouteNode } from './types';

// 首页推荐/示例场景池（30 个常见生活场景，首页随机展示 6 个）
export const EXAMPLE_SCENES: ExampleScene[] = [
  {
    id: 'cucumber',
    nameZh: '吃黄瓜',
    nameEn: 'Eating Cucumber',
    prompt: '孩子正在吃黄瓜',
    emoji: '🥒',
    hint: '孩子正吃着黄瓜，借机学几句',
  },
  {
    id: 'wakeup',
    nameZh: '起床',
    nameEn: 'Waking Up',
    prompt: '早上叫孩子起床',
    emoji: '⏰',
    hint: '叫醒孩子的早晨小对话',
  },
  {
    id: 'brush',
    nameZh: '刷牙',
    nameEn: 'Brushing Teeth',
    prompt: '孩子准备刷牙',
    emoji: '🪥',
    hint: '刷牙时的亲子英语',
  },
  {
    id: 'breakfast',
    nameZh: '吃早餐',
    nameEn: 'Breakfast',
    prompt: '一家人正在吃早餐',
    emoji: '🍳',
    hint: '早餐桌上的日常英语',
  },
  {
    id: 'leaving',
    nameZh: '出门上学',
    nameEn: 'Leaving for School',
    prompt: '孩子准备出门上学',
    emoji: '🎒',
    hint: '出门前的叮嘱与告别',
  },
  {
    id: 'snack',
    nameZh: '吃点心',
    nameEn: 'Snack Time',
    prompt: '孩子下午想吃点心',
    emoji: '🍪',
    hint: '点心时间的简单对话',
  },
  {
    id: 'lunch',
    nameZh: '吃午饭',
    nameEn: 'Eating Lunch',
    prompt: '一家人正在吃午饭',
    emoji: '🍽️',
    hint: '午餐时间的亲子对话',
  },
  {
    id: 'dinner',
    nameZh: '吃晚饭',
    nameEn: 'Dinner Time',
    prompt: '一家人正在吃晚饭',
    emoji: '🍲',
    hint: '晚餐桌上的温馨对话',
  },
  {
    id: 'bath',
    nameZh: '洗澡',
    nameEn: 'Taking a Bath',
    prompt: '孩子准备洗澡',
    emoji: '🛁',
    hint: '洗澡时的玩乐英语',
  },
  {
    id: 'bedtime',
    nameZh: '睡觉',
    nameEn: 'Bedtime',
    prompt: '孩子准备睡觉',
    emoji: '🛏️',
    hint: '睡前故事与晚安对话',
  },
  {
    id: 'homework',
    nameZh: '写作业',
    nameEn: 'Doing Homework',
    prompt: '孩子正在写作业',
    emoji: '📝',
    hint: '辅导作业时的英语对话',
  },
  {
    id: 'reading',
    nameZh: '读绘本',
    nameEn: 'Reading a Book',
    prompt: '和孩子一起读绘本',
    emoji: '📖',
    hint: '亲子阅读时的简单英语',
  },
  {
    id: 'dressup',
    nameZh: '穿衣服',
    nameEn: 'Getting Dressed',
    prompt: '孩子正在穿衣服',
    emoji: '👕',
    hint: '穿衣服时的日常对话',
  },
  {
    id: 'shoes',
    nameZh: '穿鞋',
    nameEn: 'Putting on Shoes',
    prompt: '孩子正在穿鞋',
    emoji: '👟',
    hint: '出门前穿鞋的小对话',
  },
  {
    id: 'washhands',
    nameZh: '洗手',
    nameEn: 'Washing Hands',
    prompt: '孩子准备洗手',
    emoji: '🧼',
    hint: '饭前便后洗手的好习惯',
  },
  {
    id: 'playtoys',
    nameZh: '玩玩具',
    nameEn: 'Playing with Toys',
    prompt: '孩子正在玩玩具',
    emoji: '🧸',
    hint: '玩玩具时的互动英语',
  },
  {
    id: 'blocks',
    nameZh: '搭积木',
    nameEn: 'Building Blocks',
    prompt: '孩子正在搭积木',
    emoji: '🧱',
    hint: '搭积木时的创意对话',
  },
  {
    id: 'drawing',
    nameZh: '画画',
    nameEn: 'Drawing',
    prompt: '孩子正在画画',
    emoji: '🎨',
    hint: '画画时的色彩与形状英语',
  },
  {
    id: 'park',
    nameZh: '去公园',
    nameEn: 'Going to the Park',
    prompt: '带孩子去公园玩',
    emoji: '🌳',
    hint: '公园里的户外英语',
  },
  {
    id: 'supermarket',
    nameZh: '逛超市',
    nameEn: 'At the Supermarket',
    prompt: '带孩子逛超市',
    emoji: '🛒',
    hint: '超市购物时的生活英语',
  },
  {
    id: 'rain',
    nameZh: '下雨天',
    nameEn: 'Rainy Day',
    prompt: '外面下雨了',
    emoji: '🌧️',
    hint: '下雨天的室内对话',
  },
  {
    id: 'umbrella',
    nameZh: '打伞',
    nameEn: 'Using an Umbrella',
    prompt: '下雨天打伞出门',
    emoji: '☂️',
    hint: '雨天出行的注意事项',
  },
  {
    id: 'cold',
    nameZh: '天冷了',
    nameEn: 'Cold Weather',
    prompt: '天气变冷了',
    emoji: '🧣',
    hint: '天冷加衣的温馨提醒',
  },
  {
    id: 'hot',
    nameZh: '天热了',
    nameEn: 'Hot Weather',
    prompt: '天气很热',
    emoji: '☀️',
    hint: '夏天的防暑对话',
  },
  {
    id: 'sick',
    nameZh: '生病了',
    nameEn: 'Feeling Sick',
    prompt: '孩子生病不舒服',
    emoji: '🤒',
    hint: '生病时的关心与就医',
  },
  {
    id: 'medicine',
    nameZh: '吃药',
    nameEn: 'Taking Medicine',
    prompt: '孩子需要吃药',
    emoji: '💊',
    hint: '吃药时的安抚对话',
  },
  {
    id: 'tv',
    nameZh: '看电视',
    nameEn: 'Watching TV',
    prompt: '孩子想看电视',
    emoji: '📺',
    hint: '看电视的时间约定',
  },
  {
    id: 'phone',
    nameZh: '玩手机',
    nameEn: 'Using the Phone',
    prompt: '孩子想玩手机',
    emoji: '📱',
    hint: '电子产品的使用约定',
  },
  {
    id: 'friends',
    nameZh: '找朋友玩',
    nameEn: 'Playing with Friends',
    prompt: '孩子想找朋友玩',
    emoji: '👫',
    hint: '社交场景的英语对话',
  },
  {
    id: 'cleanup',
    nameZh: '收拾玩具',
    nameEn: 'Cleaning Up',
    prompt: '孩子收拾玩具',
    emoji: '🧹',
    hint: '养成整理好习惯的对话',
  },
];

// 从场景池中随机抽取 n 个不重复的场景
export function pickRandomScenes(count: number): ExampleScene[] {
  const pool = [...EXAMPLE_SCENES];
  const result: ExampleScene[] = [];
  const n = Math.min(count, pool.length);
  for (let i = 0; i < n; i++) {
    const idx = Math.floor(Math.random() * pool.length);
    result.push(pool.splice(idx, 1)[0]);
  }
  return result;
}

// 默认上学日生活路线节点
export const DEFAULT_ROUTE_NODES: RouteNode[] = [
  {
    id: 'wakeup',
    nameZh: '起床',
    nameEn: 'Waking Up',
    desc: '叫醒孩子，开启新的一天',
    time: '07:00',
    emoji: '⏰',
  },
  {
    id: 'brush',
    nameZh: '刷牙洗脸',
    nameEn: 'Brushing Teeth',
    desc: '洗漱时间，养成好习惯',
    time: '07:15',
    emoji: '🪥',
  },
  {
    id: 'breakfast',
    nameZh: '吃早餐',
    nameEn: 'Breakfast',
    desc: '一家人围坐吃早餐',
    time: '07:30',
    emoji: '🍳',
  },
  {
    id: 'dressup',
    nameZh: '换衣服',
    nameEn: 'Getting Dressed',
    desc: '穿好校服，整理书包',
    time: '08:00',
    emoji: '👕',
  },
  {
    id: 'leaving',
    nameZh: '出门上学',
    nameEn: 'Leaving for School',
    desc: '出门前的叮嘱与告别',
    time: '08:20',
    emoji: '🎒',
  },
  {
    id: 'school',
    nameZh: '到学校',
    nameEn: 'At School',
    desc: '和老师同学打招呼',
    time: '08:50',
    emoji: '🏫',
  },
];

// 默认周末生活路线节点
export const WEEKEND_ROUTE_NODES: RouteNode[] = [
  {
    id: 'wk-wakeup',
    nameZh: '自然醒',
    nameEn: 'Waking Up Naturally',
    desc: '周末不用赶时间，慢慢起床',
    time: '08:30',
    emoji: '😴',
  },
  {
    id: 'wk-breakfast',
    nameZh: '做早餐',
    nameEn: 'Making Breakfast',
    desc: '一起准备周末早餐',
    time: '09:00',
    emoji: '🥞',
  },
  {
    id: 'wk-play',
    nameZh: '在家玩耍',
    nameEn: 'Playing at Home',
    desc: '搭积木、画画、玩玩具',
    time: '10:00',
    emoji: '🧸',
  },
  {
    id: 'wk-outdoor',
    nameZh: '出门活动',
    nameEn: 'Outdoor Activity',
    desc: '去公园、骑车、散步',
    time: '14:00',
    emoji: '🌳',
  },
  {
    id: 'wk-snack',
    nameZh: '下午茶点',
    nameEn: 'Afternoon Snack',
    desc: '休息一下吃点东西',
    time: '15:30',
    emoji: '🍪',
  },
  {
    id: 'wk-bath',
    nameZh: '洗澡时间',
    nameEn: 'Bath Time',
    desc: '玩水洗澡，放松一下',
    time: '18:30',
    emoji: '🛁',
  },
  {
    id: 'wk-story',
    nameZh: '睡前故事',
    nameEn: 'Bedtime Story',
    desc: '一起读绘本讲故事',
    time: '20:00',
    emoji: '📖',
  },
];
